version: '3.9'

services:

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    restart: always
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: bash -c "/wait-for-it.sh db:5432 &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/backend
      - ./backend/wait-for-it.sh:/wait-for-it.sh
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    command : npm start
    ports:
      - "3000:3000"
    depends_on:
      - api