# Generated by Django 4.0.2 on 2022-02-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visualisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.IntegerField(default=30)),
                ('steps', models.IntegerField(default=100)),
            ],
        ),
    ]
