# Generated by Django 3.1.2 on 2022-03-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellularAutomaton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.IntegerField(default=30)),
                ('steps', models.IntegerField(default=100)),
                ('binary_plot', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.DeleteModel(
            name='Visualisation',
        ),
    ]
