# Generated by Django 3.1.2 on 2022-03-01 13:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automata', '0002_auto_20220301_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellularautomaton',
            name='binary_plot',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 0), (1, 1)]), size=None), size=None),
        ),
    ]
