# Generated by Django 3.1.2 on 2022-03-01 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automata', '0003_auto_20220301_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellularautomaton',
            name='rule',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='cellularautomaton',
            name='steps',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
