# Generated by Django 3.1.2 on 2022-03-01 14:08

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automata', '0004_auto_20220301_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellularautomaton',
            name='binary_plot',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Zero'), (1, 'One')]), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='cellularautomaton',
            name='rule',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1, message='Rule number must be greater than or equal to 1.')]),
        ),
        migrations.AlterField(
            model_name='cellularautomaton',
            name='steps',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1, message='Number of steps must be greater than or equal to 1.')]),
        ),
    ]
