# Generated by Django 3.1.2 on 2022-03-01 15:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automata', '0006_auto_20220301_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellularautomaton',
            name='binary_plot',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='cellularautomaton',
            name='rule',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='cellularautomaton',
            name='steps',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
