# Generated by Django 3.1.2 on 2022-03-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automata', '0007_auto_20220301_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellularautomaton',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
