# Generated by Django 3.1.2 on 2022-03-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automata', '0009_remove_cellularautomaton_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellularautomaton',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
