# Generated by Django 3.1.2 on 2022-03-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automata', '0010_cellularautomaton_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cellularautomaton',
            old_name='date',
            new_name='date_time',
        ),
    ]
