# Generated by Django 3.1.2 on 2022-03-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automata', '0011_auto_20220308_1829'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cellularautomaton',
            unique_together={('rule', 'steps')},
        ),
    ]
